/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPokemonsIndexRouteImport } from './routes/_authenticated/pokemons/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedBerriesIndexRouteImport } from './routes/_authenticated/berries/index'
import { Route as AuthenticatedPokemonsIdRouteImport } from './routes/_authenticated/pokemons/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPokemonsIndexRoute =
  AuthenticatedPokemonsIndexRouteImport.update({
    id: '/pokemons/',
    path: '/pokemons/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBerriesIndexRoute =
  AuthenticatedBerriesIndexRouteImport.update({
    id: '/berries/',
    path: '/berries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPokemonsIdRoute = AuthenticatedPokemonsIdRouteImport.update({
  id: '/pokemons/$id',
  path: '/pokemons/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons/$id': typeof AuthenticatedPokemonsIdRoute
  '/berries': typeof AuthenticatedBerriesIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/pokemons': typeof AuthenticatedPokemonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons/$id': typeof AuthenticatedPokemonsIdRoute
  '/berries': typeof AuthenticatedBerriesIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/pokemons': typeof AuthenticatedPokemonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/pokemons/$id': typeof AuthenticatedPokemonsIdRoute
  '/_authenticated/berries/': typeof AuthenticatedBerriesIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/pokemons/': typeof AuthenticatedPokemonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemons/$id' | '/berries' | '/items' | '/pokemons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemons/$id' | '/berries' | '/items' | '/pokemons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/pokemons/$id'
    | '/_authenticated/berries/'
    | '/_authenticated/items/'
    | '/_authenticated/pokemons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pokemons/': {
      id: '/_authenticated/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof AuthenticatedPokemonsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/berries/': {
      id: '/_authenticated/berries/'
      path: '/berries'
      fullPath: '/berries'
      preLoaderRoute: typeof AuthenticatedBerriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pokemons/$id': {
      id: '/_authenticated/pokemons/$id'
      path: '/pokemons/$id'
      fullPath: '/pokemons/$id'
      preLoaderRoute: typeof AuthenticatedPokemonsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPokemonsIdRoute: typeof AuthenticatedPokemonsIdRoute
  AuthenticatedBerriesIndexRoute: typeof AuthenticatedBerriesIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedPokemonsIndexRoute: typeof AuthenticatedPokemonsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPokemonsIdRoute: AuthenticatedPokemonsIdRoute,
  AuthenticatedBerriesIndexRoute: AuthenticatedBerriesIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedPokemonsIndexRoute: AuthenticatedPokemonsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
