/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailsIndexRouteImport } from './routes/details/index'
import { Route as DetailsPokemonNameRouteImport } from './routes/details/$pokemonName'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsIndexRoute = DetailsIndexRouteImport.update({
  id: '/details/',
  path: '/details/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsPokemonNameRoute = DetailsPokemonNameRouteImport.update({
  id: '/details/$pokemonName',
  path: '/details/$pokemonName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/details/$pokemonName': typeof DetailsPokemonNameRoute
  '/details/': typeof DetailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/details/$pokemonName': typeof DetailsPokemonNameRoute
  '/details': typeof DetailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/details/$pokemonName': typeof DetailsPokemonNameRoute
  '/details/': typeof DetailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/details/$pokemonName' | '/details/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/details/$pokemonName' | '/details'
  id: '__root__' | '/' | '/home' | '/details/$pokemonName' | '/details/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  DetailsPokemonNameRoute: typeof DetailsPokemonNameRoute
  DetailsIndexRoute: typeof DetailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/': {
      id: '/details/'
      path: '/details'
      fullPath: '/details/'
      preLoaderRoute: typeof DetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$pokemonName': {
      id: '/details/$pokemonName'
      path: '/details/$pokemonName'
      fullPath: '/details/$pokemonName'
      preLoaderRoute: typeof DetailsPokemonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  DetailsPokemonNameRoute: DetailsPokemonNameRoute,
  DetailsIndexRoute: DetailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
